# .github/workflows/build_test.yml
name: Build and Test orbslam3

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch: # Allows manual triggering

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04] # Use specific OS versions for stability [W.I.P]  windows-latest, macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive" # This is critical for pulling in ORB_SLAM3_engine

      - name: Set up QEMU (for ARM builds on Linux)
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.0.0
        env:
          # Install system-level dependencies for ORB-SLAM3 on Linux before building
          CIBW_BEFORE_BUILD_LINUX: >
            apt-get update && apt-get install -y
            libeigen3-dev
            libopencv-dev
            libboost-serialization-dev 
            liboctomap-dev 
            libssl-dev

          # Skip architectures that might not be supported by dependencies
          CIBW_ARCHS_LINUX: "auto aarch64"
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_ARCHS_WINDOWS: "AMD64"

          # Skip musl builds as they often have linking issues with complex C++
          CIBW_SKIP: "*-musllinux_*"

      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl
