# .github/workflows/build-test.yml

name: Build and Test

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ] # Runs on pushes to the main branch
  pull_request:
    branches: [ "main" ] # Runs on pull requests targeting the main branch

jobs:
  build:
    # Use a matrix to test on multiple Python versions and operating systems
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.10", "3.12"] # Versions from your pyproject.toml
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      # --- 1. Set up the environment ---
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          # Required for fetching the ORB_SLAM3_engine submodule
          submodules: 'recursive'

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # --- 2. Install Dependencies ---
      - name: Install system dependencies
        run: |
          chmod +x ./apt-dependencies.sh
          sudo ./apt-dependencies.sh

      - name: Install Python build tools and test dependencies
        run: |
          python -m pip install --upgrade pip
          # Installs project in editable mode and pytest/numpy from optional-dependencies
          pip install -e .[test]

      # --- 3. Prepare Test Data ---
      - name: Download and set up test dataset
        run: |
          wget https://vision.in.tum.de/rgbd/dataset/freiburg1/rgbd_dataset_freiburg1_xyz.tgz
          tar -xvf rgbd_dataset_freiburg1_xyz.tgz
          mkdir -p test/data/TUM1_xyz/rgb
          find rgbd_dataset_freiburg1_xyz/rgb -name "*.png" | sort | head -n 10 | xargs -I {} cp {} test/data/TUM1_xyz/rgb/
          rm -rf rgbd_dataset_freiburg1_xyz.tgz rgbd_dataset_freiburg1_xyz

      # --- 4. Run Tests ---
      - name: Run Pytest
        run: |
          pytest